---
# Lesson 4: Using Templates with Jinja2
# Learn how to create dynamic configuration files

- name: Template Demonstration
  hosts: local
  gather_facts: yes

  vars:
    app_name: "WebServer"
    app_version: "2.1.0"
    server_port: 80
    max_connections: 1000
    enable_ssl: true
    admin_email: "admin@example.com"
    allowed_hosts:
      - "localhost"
      - "127.0.0.1"
      - "example.com"

  tasks:
    - name: Create templates directory
      file:
        path: /tmp/ansible-templates
        state: directory
        mode: '0755'

    - name: Generate configuration from template
      template:
        src: templates/app-config.j2
        dest: /tmp/ansible-templates/app-config.conf
        mode: '0644'

    - name: Generate HTML page from template
      template:
        src: templates/index.html.j2
        dest: /tmp/ansible-templates/index.html
        mode: '0644'

    - name: Display the generated configuration
      command: cat /tmp/ansible-templates/app-config.conf
      register: config_content
      changed_when: false

    - name: Show configuration content
      debug:
        msg: "{{ config_content.stdout_lines }}"
