---
# Lesson 6: Comprehensive Example
# This playbook combines multiple Ansible concepts

- name: Deploy a Simple Web Application
  hosts: local
  gather_facts: yes
  become: no

  vars:
    app_name: "TrainingApp"
    app_version: "1.0.0"
    app_dir: /tmp/training-app
    config_dir: "{{ app_dir }}/config"
    data_dir: "{{ app_dir }}/data"
    log_dir: "{{ app_dir }}/logs"

    app_settings:
      port: 8080
      debug: true
      max_users: 100
      session_timeout: 3600

    environments:
      - name: development
        debug: true
      - name: staging
        debug: false
      - name: production
        debug: false

  tasks:
    - name: Display deployment information
      debug:
        msg: |
          ====================================
          Deploying {{ app_name }} v{{ app_version }}
          Target: {{ ansible_hostname }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Time: {{ ansible_date_time.iso8601 }}
          ====================================

    - name: Create application directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ app_dir }}"
        - "{{ config_dir }}"
        - "{{ data_dir }}"
        - "{{ log_dir }}"

    - name: Deploy application script
      copy:
        content: |
          #!/bin/bash
          # {{ app_name }} v{{ app_version }}
          # Generated by Ansible on {{ ansible_date_time.date }}

          echo "Starting {{ app_name }}..."
          echo "Listening on port {{ app_settings.port }}"
          echo "Debug mode: {{ app_settings.debug }}"
          echo "Application is running. Press Ctrl+C to stop."

          # Simulate running application
          tail -f /dev/null
        dest: "{{ app_dir }}/start.sh"
        mode: '0755'

    - name: Create configuration files for each environment
      copy:
        content: |
          # {{ app_name }} Configuration - {{ item.name }} environment

          [application]
          name={{ app_name }}
          version={{ app_version }}
          environment={{ item.name }}

          [server]
          port={{ app_settings.port }}
          debug={{ item.debug }}
          max_users={{ app_settings.max_users }}
          session_timeout={{ app_settings.session_timeout }}

          [paths]
          data_dir={{ data_dir }}
          log_dir={{ log_dir }}

          [deployment]
          deployed_by=Ansible
          deployed_at={{ ansible_date_time.iso8601 }}
          deployed_on={{ ansible_hostname }}
        dest: "{{ config_dir }}/{{ item.name }}.conf"
        mode: '0644'
      loop: "{{ environments }}"

    - name: Create initial log file
      lineinfile:
        path: "{{ log_dir }}/application.log"
        line: "{{ ansible_date_time.iso8601 }} [INFO] Application deployed"
        create: yes
        mode: '0644'

    - name: Create a sample data file
      copy:
        content: |
          # Sample Data File
          timestamp,event,status
          {{ ansible_date_time.epoch }},deployment,success
          {{ ansible_date_time.epoch }},configuration,complete
          {{ ansible_date_time.epoch }},startup,ready
        dest: "{{ data_dir }}/events.csv"
        mode: '0644'

    - name: Generate deployment report
      copy:
        content: |
          ========================================
          DEPLOYMENT REPORT
          ========================================

          Application: {{ app_name }}
          Version: {{ app_version }}

          System Information:
          - Hostname: {{ ansible_hostname }}
          - OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Architecture: {{ ansible_architecture }}
          - CPU Cores: {{ ansible_processor_vcpus }}
          - Total Memory: {{ ansible_memtotal_mb }} MB

          Deployment Details:
          - Time: {{ ansible_date_time.iso8601 }}
          - User: {{ ansible_user_id }}
          - Working Directory: {{ ansible_env.PWD }}

          Application Settings:
          - Port: {{ app_settings.port }}
          - Debug: {{ app_settings.debug }}
          - Max Users: {{ app_settings.max_users }}
          - Session Timeout: {{ app_settings.session_timeout }}s

          Directories Created:
          - Application: {{ app_dir }}
          - Configuration: {{ config_dir }}
          - Data: {{ data_dir }}
          - Logs: {{ log_dir }}

          Environments Configured: {{ environments | length }}
          {% for env in environments %}
          - {{ env.name }} (debug: {{ env.debug }})
          {% endfor %}

          ========================================
          Deployment completed successfully!
          ========================================
        dest: "{{ app_dir }}/DEPLOYMENT_REPORT.txt"
        mode: '0644'

    - name: Display deployment summary
      debug:
        msg:
          - "Deployment completed successfully!"
          - "Application directory: {{ app_dir }}"
          - "View the deployment report: {{ app_dir }}/DEPLOYMENT_REPORT.txt"
          - "Start the application: {{ app_dir }}/start.sh"

    - name: Verify all files were created
      find:
        paths: "{{ app_dir }}"
        recurse: yes
        file_type: file
      register: deployed_files

    - name: Show deployment statistics
      debug:
        msg: "Total files deployed: {{ deployed_files.files | length }}"
